/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "cpplib.h"
#include <cassert>

int main() {
    jniexample::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World! From C++") == 0);
    return 0;
}
