language: java
install: skip
sudo: false

os: linux
dist: trusty

jdk:
  - openjdk17
git:
  quiet: true
jobs:
  fast_finish: true

script:
#openal
  - sudo apt-get -y install libopenal-dev

#python
  - sudo apt-get -y install libpython3.9 --fix-missing
  - sudo apt-get -y install libpython3.10
  - sudo apt-get -y install libpython3.10-dev
  - sudo apt-get -y install libpython3.10-stdlib

#pip
  - sudo wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
  - sudo python3 get-pip.py
  - sudo python3 -m pip install --upgrade pip
  - sudo python3 -m pip install --upgrade setuptools 
  - sudo python3 -m pip install --upgrade wheel

#build tools
  - sudo python3 -m pip install meson
  - sudo python3 -m pip install ninja
  - sudo python3 -m pip install cmake
  - sudo mkdir -p build/gtk4
  - sudo mkdir -p build/glib2
  - sudo mkdir -p build/pango
  - sudo mkdir -p build/vulkan

#gradle
  - chmod +x ./gradlew && ./gradlew build