language: java
install: skip
sudo: false

os: linux
dist: jammy

jdk:
  - openjdk17
git:
  quiet: true
jobs:
  fast_finish: true

script:
#ncurses
  - sudo chmod 777 gradlew
  - sudo apt-get -y install libncurses5 libncurses5-dev libncursesw5-dev
  - sudo apt-get -y update

#openal
  - sudo apt-get -y install libopenal-dev

#gcc multilib
  - sudo apt-get -y install gcc-multilib g++-multilib

#python
  - sudo apt-get -y install libpython3.10 --fix-missing
  - sudo apt-get -y install python3.10-full
  - sudo apt-get -y install python3.10-dev

#pip
  - sudo wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade setuptools 
  - python3 -m pip install --upgrade wheel

#midi
  - sudo apt-get -y install libjack-dev librtmidi-dev librtmidi6
  - sudo apt-get -y install libalsaplayer-dev libasound2-dev

#mathgl
  - sudo apt-get -y install mathgl

#vulkan
  - sudo apt-get -y install libvulkan1 libvulkan-dev vulkan-validationlayers vulkan-validationlayers-dev

#rsvg
  - sudo apt-get -y install librsvg2-dev

#gtk4
  - sudo apt-get -y install libgtk-4-1

#gradle
  - sudo ./gradlew build --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache -Dkotlin.colors.enabled=false -Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2
