language: java
install: skip
sudo: false

os: linux
dist: bionic

jdk:
  - openjdk17
git:
  quiet: true
jobs:
  fast_finish: true

script:
#openjdk8
  - sudo chmod 777 gradlew
  - sudo apt-get -y install libncurses5
  - sudo apt-get update

#openal
  - sudo apt-get -y install libopenal-dev

#python
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -y install libpython3.10 --fix-missing
  - sudo apt-get -y install python3.10-full
  - sudo apt-get -y install python3.10-dev

#pip
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
  - python3.10 get-pip.py
  - python3.10 -m pip install --upgrade pip
  - python3.10 -m pip install --upgrade setuptools 
  - python3.10 -m pip install --upgrade wheel

#build tools
  - python3.10 -m pip install meson
  - python3.10 -m pip install ninja
  - python3.10 -m pip install cmake
  - sudo mkdir -p build/gtk4
  - sudo mkdir -p build/glib2
  - sudo mkdir -p build/pango
  - sudo mkdir -p build/vulkan

#gradle
  - ./gradlew assemble
