language: java
install: skip
sudo: false

os: linux
dist: jammy

jdk:
  - openjdk17
git:
  quiet: true
jobs:
  fast_finish: true

script:
#ncurses
  - sudo chmod 777 gradlew
  - sudo apt-get -y install libncurses5
  - sudo apt-get -y update

#openal
  - sudo apt-get -y install libopenal-dev

#python
  - sudo apt-get -y install libpython3.10 --fix-missing
  - sudo apt-get -y install python3.10-full
  - sudo apt-get -y install python3.10-dev

#pip
  - wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - python3 -m pip install --upgrade pip
  - python3 -m pip install --upgrade setuptools 
  - python3 -m pip install --upgrade wheel

#build tools
  - python3 -m pip install meson
  - python3 -m pip install ninja
  - python3 -m pip install cmake
  - sudo mkdir -p build/gtk4
  - sudo mkdir -p build/glib2
  - sudo mkdir -p build/pango
  - sudo mkdir -p build/vulkan

#midi
  - sudo apt-get -y install libjack-dev libtool bzip2 m4 automake
  - sudo apt-get -y install libalsaplayer-dev libasound2-dev
  - sudo mkdir -p build/rtmidi
  - sudo git clone https://github.com/thestk/rtmidi.git build/rtmidi
  - sudo git --work-tree=build/rtmidi --git-dir=build/rtmidi/.git checkout tags/4.0.0 -b 4.0.0
  - sudo chmod -R 755 build
  - cd build/rtmidi
  - sudo ./autogen.sh
  - sudo ./configure --prefix=/usr
  - sudo make
  - sudo make install
  - cd ../..

#gradle
  - sudo ./gradlew build
