/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "cpplib.h"
#include <cassert>
#include <string.h>
#include <iostream>

int main() {
	CppLib::Library lib;
	std::string str("Hello, World! From C++");
	std::string str1(lib.greeting());
	std::cout<<str1;
    assert(strcmp( lib.greeting(), str.c_str()) == 0);
    return 0;
}
