/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "cpplib.h"
#include <cassert>

int main() {
	CppLib::Library lib;
    assert(lib.greeting().compare("Hello, World! From C++") == 0);
    return 0;
}
