/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "cpplib.h"

std::string jniexample::Greeter::greeting() {
    return std::string("Hello, World! From C++");
}
