/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef JNIEXAMPLE_H
#define JNIEXAMPLE_H

#ifdef _WIN32
#define JNIEXAMPLE_EXPORT_FUNC __declspec(dllexport)
#else
#define JNIEXAMPLE_EXPORT_FUNC
#endif

#include <string>

namespace jniexample {
    class Greeter {
        public:
        std::string JNIEXAMPLE_EXPORT_FUNC greeting();
    };
}

#endif
